# Generated by Django 4.1.5 on 2023-01-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='testset',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='sort order'),
        ),
    ]
